sudo: required
services:
  - docker

before_install:
  - docker build -t jsur/flashcards -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jsur/flashcards npm test -- --coverage --watchAll=false

after_success:
  - docker build -t jsur/flashcards-client ./client
  - docker build -t jsur/flashcards-nginx ./nginx
  - docker build -t jsur/flashcards-server ./server
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD"|docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push jsur/flashcards-client
  - docker push jsur/flashcards-nginx
  - docker push jsur/flashcards-server